### ISSUE TITLE
config file is not clear

### ISSUE THREAD

**Issue by SolarisYan** [cznewt/architect-api#3]
Hi, i read the install document at here [https://architect-api.readthedocs.io/en/latest/text/app-install.html](url), but i think the config file is not clear,so i can't  install it for test, maybe i can guess it.
now i use saltstack to manage openstack, vcenter and kubenetes, and I know more about those.Can you provide some example config files, it would be better. Thanks a lot

**Comment by cznewt** [comment]
Hello, I've overhauled the installation documentation http://architect-api.readthedocs.io/en/latest/text/app-install.html, i'm transforming ui to bootstrap 4, some glitches may appear, but app should be installable, if not, let me please know.

**Comment by SolarisYan** [comment]
Thanks a lot, i will test it again
